### ISSUE TITLE
Bug v1.3.2

### ISSUE THREAD

**Issue by iLiDanMoon** [HyChrod/Friends#6]
[16:04:34] [Craft Scheduler Thread - 518/WARN]: [FriendsRELOADED] Plugin FriendsRELOADED v1.3.2 generated an exception while executing task 1759530
java.lang.NullPointerException: null
	at de.HyChrod.Friends.Listeners.JoinListener$2.run(JoinListener.java:50) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-86]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-86]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-86]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by HyChrod** [comment]
#Fixed in 1.3.3
